server:
  port: 4444


spring:
  application:
    name: hello-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka/
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
